### ISSUE TITLE
using images from disk rather then taking from webcam

### ISSUE THREAD

**Issue by anju54** [susantabiswas/FaceRecog#1]
Error when checking : expected input_1 to have shape (None, 3, 96, 96) but got array with shape (1, 3, 90, 70)
getting this error in add_user_image_path funtion
can u help me to fix it

**Comment by adibyte95** [comment]
the shape of the image that you are using has to be (3,96,96) where 3 is the no of channels and (96,96) is the height and width of the image .... but the image which you are passing has a dimension of (3,90,70) i.e (90,70) is the height and width. thus there is mismatch.. you can resize your image to fit the required dimensions for ex-using OpenCV resize function

**Comment by anju54** [comment]
(None, 3, 96, 96)  what is None here??/

**Comment by adibyte95** [comment]
input_1 layer expects any number of input images . So for 1 image shape will be (1,3,96,96) for 2 images input will be (2,3,96,96) as it expects any no of images it keeps first parameter None as if it doesn't care about the no of images you are supplying but only the dimensions of every image

**Comment by susantabiswas** [comment]
@anjuasadel here is a code snippet for checking using an image from disk:
### Run this in the Face_recognition.ipynb notebook as a cell
```
path = "your path here"
resize_img(path)
encoding = img_to_encoding(path, FRmodel)

threshold = 0.7
min_dist = 99999
# loop over all the recorded encodings in database
for name in database:
    # find the similarity between the input encodings and claimed person's encodings using L2 norm
    dist = np.linalg.norm(np.subtract(database[name], encoding))
    # check if minimum distance or not
    if dist < min_dist:
        min_dist = dist
        identity = name

if min_dist > threshold:
    print("User not in the database.")
    identity = 'Unknown Person'
else:
    print("Hi! " + str(identity) + ", L2 distance: " + str(min_dist))
    
print('Identity: ' + str(identity))
print('Min distance: ' + str(min_dist))
```
