### ISSUE TITLE
Error while restoring model

### ISSUE THREAD

**Issue by Backalla** [susantabiswas/FaceRecog#2]
I am getting the following error while restoring the model. 
The file for inception_blocks_v2 was also missing and could not be imported. I downloaded it from [here](https://github.com/JudasDie/deeplearning.ai/blob/master/Convolutional%20Neural%20Networks/week4/FaceNet/inception_blocks_v2.py) and also its dependency fr_utils.py. 

ValueError: Shape must be rank 1 but is rank 4 for 'bn1/cond/FusedBatchNorm' (op: 'FusedBatchNorm') with input shapes: [?,64,48,48], [1,64,1,1], [1,64,1,1], [1,64,1,1], [1,64,1,1].
Using Keras 2.2.0, Tensorflow 1.8.0

**Comment by susantabiswas** [comment]
Fixed, you can check now.

**Comment by Backalla** [comment]
Thanks for the resolution.. :+1: 
Although, Even I removed that import but the error is in restoring the model at line
FRmodel = load_model('models/model.h5', custom_objects={'triplet_loss': triplet_loss}). Is there an updated model file?

**Comment by luis0893** [comment]
because it takes too long to load the model, is there no way to speed up the loading of the model? I want to put it into production and it would take me to consume it. Please if you can help me. Thank you

**Comment by susantabiswas** [comment]
@luisito93 what file are you using for running the code and are you able to load the model?
