### ISSUE TITLE
ValueError while loading model.

### ISSUE THREAD

**Issue by Backalla** [susantabiswas/FaceRecog#3]
ValueError: Shape must be rank 1 but is rank 4 for 'bn1/cond/FusedBatchNorm' (op: 'FusedBatchNorm') with input shapes: [?,64,48,48], [1,64,1,1], [1,64,1,1], [1,64,1,1], [1,64,1,1].
I am using Keras 2.2.0 and Tensorflow 1.8.0. I am not able to load the model and getting an error at the following line. 
FRmodel = load_model('models/model.h5', custom_objects={'triplet_loss': triplet_loss}). Is there an updated model file?

**Comment by susantabiswas** [comment]
the problem was with incompataibility of inception file and model. I have made changes accordingly. Reclone the repo once and tell me if the problem resides. Are you running the notebook or python file?

**Comment by Backalla** [comment]
I tried both. Same problem on the same line in both the cases.. Is there another model.h5 file?

**Comment by susantabiswas** [comment]
I don't seem to reproduce your problem on my system. I cloned this repo to a different PC and the model ran straight away, the only issue was during import which was solved by removing the inception import.
The model file was the one that this repo contains.

**Comment by Backalla** [comment]
Thanks for the response.. Let me see if I can run this on a different system. I am using Python3 but I dont think that could be the issue. Is there any special requirements for this code that I might be missing?

**Comment by susantabiswas** [comment]
I did this way back on a different system and I don't remember the version requirements. But yesterday I ran this on a different system which had your usual preinstalled stuff. 
The version number on that system were: Keras 2.1.6, Tensorflow: 1.8.0, Python 3.6.5
