### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by AndreyRomanenko** [susantabiswas/FaceRecog#4]
Hi, can you help me, should i resize my phoro before add for user or need scale 96x96?
It's message when just photo
`ValueError: Error when checking input: expected input_1 to have shape (3, 96, 96) but got array with shape (3, 648, 464)`

But when i resize the photo to 96x96, it added to base but doesn't do face recognition and also have got the error with resize (empty data).

thanks for answer

**Comment by susantabiswas** [comment]
Yes according to the error, the image should be resized before feeding it to the network, but that operation is taken care by the code itself, you just need to give it the image location.
