### ISSUE TITLE
Where is the Siamese neural network？

### ISSUE THREAD

**Issue by tomjerrygithub** [susantabiswas/FaceRecog#6]
Where is the Siamese neural network？

**Comment by pradeepvarma22** [comment]
Triplet loss: https://towardsdatascience.com/siamese-network-triplet-loss-b4ca82c1aec8

code line  : 
https://github.com/susantabiswas/FaceRecog/blob/aa1b2a2a32d23ead2a2dd96353b2275ef88716c8/Face%20Recognition.py#L64

☺️

**Comment by agrija9** [comment]
Hi guys,

**I also had doubt about where exactly is the siamese network in this repository.**

There is no such thing as siamese network here (although the author claims to use it). He is actually using a Face Net with triplet loss.

In the `FaceRecognition.py` file, the author mentions:

> <u>Face Recognition System
> This is based on Siamsese network.
> The advantage of **Siamese Network** is that it allows a way to do this sort of verification task with very little user data, as it is quite unreasonable to train using thousands of images for each user. Here we will be using **FaceNet Model**.
> FaceNet learns a neural network that encodes a face image into a vector of 128 numbers. So by comparing two such vectors, we can then determine if two pictures are of the same person._

I don't know why he does this, but he does it. So the weights that he loads from the .h5 file are actually obtained by training a face net. 

Regards
